[project]
name = "workspace"
version = "0.1.0"
description = "Add your description here"
requires-python = ">=3.11"
dependencies = [
    "bcrypt>=4.3.0",
    "pandas>=2.2.3",
    "plotly>=6.0.1",
    "pyarrow>=19.0.1",
    "pycryptodome==3.21.0",
    "pyjwt>=2.10.1",
    "streamlit>=1.43.2",
]

[tool.poetry]
name = "workspace"
version = "0.1.0"
description = ""
authors = ["Your Name <you@example.com>"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.11"
streamlit = ">=1.43.2"
python-jose = {version = ">=3.4.0", extras = ["cryptography"]}
pyarrow = ">=19.0.1"
plotly = ">=6.0.1"
pandas = ">=2.2.3"
jose = ">=1.0.0"
bcrypt = ">=4.3.0"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
